### ISSUE TITLE
don't fail no connection reset/timeout

### ISSUE THREAD

**Issue by passiweinberger** [nupic-community/htmengine-traffic-tutorial#2]
this is the error I got pretty often at different points: 

```
...
Path 447: posting 1129 data points to HTM engine...
Path 442: posting 1413 data points to HTM engine...
Path 107: posted to HTM engine (151 more to go)...
Path 376: posted to HTM engine (150 more to go)...
Path 349: posted to HTM engine (149 more to go)...
Path 389: posted to HTM engine (148 more to go)...
Path 354: posted to HTM engine (147 more to go)...
Path 428: posted to HTM engine (146 more to go)...
/home/pascal/numenta-apps/htmengine-traffic-tutorial/node-client/lib/traffic-pusher.js:146
                    throw err;}
                          ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)

npm ERR! Linux 3.16.0-43-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! htmengine-node-client@1.0.0 start: `node index.js`
npm ERR! Exit status 1
...
```

May just catch that and retry after a short pause or sth.

**Comment by rhyolight** [comment]
Thanks for the report! I'll make sure to handle this gracefully.
